### ISSUE TITLE
Ignored unknown option "overrides"

### ISSUE THREAD

**Issue by SimonMayerhofer** [poalrom/grunt-prettier#10]
Hi,
I use the `.prettierrc` file for my configuration.
```
{
	'singleQuote': true,
	'useTabs': true,
	'trailingComma': 'all',
	'overrides': [
		{
			'files': '.prettierrc',
			'options': { 'parser': 'json' },
		},
		{
			'files': '.eslintrc',
			'options': { 'parser': 'json' },
		}
	]
}
```

I get the message
`Ignored unknown option '{ "overrides": [{"files":".prettierrc","options":{"parser":"json"}},{"files":".eslintrc","options":{"parser":"json"}}] }'.`

Thanks for your help and this nice grunt plugin :)

**Comment by poalrom** [comment]
Hi. Sorry for long delay. Fix this issue in 0.6 version. Thanks for using my plugin ^__^
