### ISSUE TITLE
Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by IgorProtsenkoOd** [poalrom/grunt-prettier#12]
Hello
I know in documentation to npm module required grunt version is ~0.4.5

But is there any change library can be adapted for grunt 1.0.3 or higher?

Once triggered in precommit hook output is:

```
Warning: Cannot read property 'replace' of undefined Use --force to continue. 
Aborted due to warnings.
```

Grunt 1.0.3

grunt init config:
```
prettier: {
      files: {
        src: [
          "./some_file"
        ]
      }
    },
```

grunt task:
```
  grunt.registerTask('prettier', 'Codestyle', [
    grunt.loadNpmTasks('grunt-prettier')
  ]);
```

.prettierrc.json content:
```
{
  "tabWidth": 2,
}
```

**Comment by poalrom** [comment]
Hi. I would fix it in few days

**Comment by poalrom** [comment]
Update to new version and can't reproduce this problem. Try to use 1.0 version of grunt-prettier and see, how it works in https://github.com/poalrom/grunt-prettier-example

**Comment by IgorProtsenko** [comment]
Works as expected, thank you.
