### ISSUE TITLE
Does this support the equivalent of prettier --check?

### ISSUE THREAD

**Issue by h223chen** [poalrom/grunt-prettier#14]
I want to configure a precommit task that doesn't do the actual reformat but only tells me if a file is unformatted. I can't find a way to do this with grunt-prettier, is it supported?

**Comment by poalrom** [comment]
Hi. You just can use prettier cli without grunt for this case

**Comment by h223chen** [comment]
my team uses grunt exclusively for tools so I don't want to introduce a separate cli command into our workflow . I can put together a PR for adding the optional support for a check flag if you'll review it.

**Comment by poalrom** [comment]
Yep, you can add this to task options and test for this case

**Comment by h223chen** [comment]
just an update ... i do still plan to do this, things just have been hectic at work.

**Comment by poalrom** [comment]
Published
