### ISSUE TITLE
Hot formatting not working as intended

### ISSUE THREAD

**Issue by olpeh** [poalrom/grunt-prettier#2]
I tried using hot formatting as mentioned in the repository and had a setup similar to this in my Gruntfile:
```
src: [
  "my-awesome-project/**.js",
  "!my-awesome-project/**.config.js"
]
```

What happened: The formatted JS was written concatenated into one file called src.

Expected behaviour: Write formatted contents back to each file.

Versions:
```
grunt-prettier@0.1.0
grunt v0.4.5
```

**Comment by poalrom** [comment]
In our project, we use this config. It works like expected for us.  

```js
grunt.config("prettier", {
        options: {
            tabWidth: 4
        },
        grunt_files: {
            src: ["Gruntfile.js", "build/grunt-tasks/*.js"]
        },
        admin: {
            src: ["public/static/admin/src/**/*.js"]
        },
        front: {
            src: ["public/static/front/src/**/*.js"]
        }
    });
```


Versions:
```
grunt-prettier@0.1.0
grunt v0.4.5
```

**Comment by olpeh** [comment]
Okay, with your example config it works, but not without that one more level there.
I don't think the readme is clear enough.

This would not work:
```
prettier: {
        options: {
            tabWidth: 4
        },
        src: ["Gruntfile.js", "build/grunt-tasks/*.js"]
    }
```  

Can you please add a more clearer example config to the readme.

But thanks for helping, it works now. 👍

**Comment by simmone** [comment]
this works:
  files: {
     src: ["js/**.js"]
   }
