### ISSUE TITLE
How to provide configuration file .prettierrc 

### ISSUE THREAD

**Issue by knlodha** [poalrom/grunt-prettier#3]
Is there any way to provide configuration file ( https://github.com/prettier/prettier#configuration-file ) 
using grunt-prettier

**Comment by poalrom** [comment]
No, there is no way now. I want to add this feature in early October

**Comment by knlodha** [comment]
@poalrom Thanks for the update

**Comment by peterssonjesper** [comment]
Until then, you could add something like this to your Gruntfile:

```javascript
var prettierConfig = grunt.file.readJSON('.prettierrc');

grunt.initConfig({
  ...
  prettier: {
   options: prettierConfig,
   ...
  }
});
```

**Comment by poalrom** [comment]
Sorry for delay. I add prettierrc support. It should be work, if you place your .prettierrc file near Gruntfile.js
Later I want to add test for this feature

**Comment by knlodha** [comment]
Thanks a lot

**Comment by jnachtigall** [comment]
@poalrom 

This is not working for me. My setup is as follows:
```
|- .prettierrc
|- Gruntfile.js (which includes the stuff below)
|--- tasks/config/prettier.js
```


And prettier.js is then 
```
module.exports = function(grunt) {
  grunt.config.set('prettier', {
    options: {
      singleQuote: true
    },
    files: {
      src: [
        '*.js',
        // this causes a bug in package.json:
        // '*.json',
        'tasks/**/*.js',
        'tasks/**/*.json',
        'src/components/**/*.js',
        'src/components/**/*.json'
      ]
    }
  });

  grunt.loadNpmTasks('grunt-prettier');
};
```

OTOH, I installed using npm and I do not see releases here. Maybe https://www.npmjs.com/package/grunt-prettier does not have the right version? It says:
> poalrom poalrom published 6 months ago 

Damn, guess that's why...

Could you please update npm? Maybe using https://www.npmjs.com/package/release-it for this.

**Comment by poalrom** [comment]
Yes, I will update it tomorrow
