### ISSUE TITLE
glob matching with *.(js|json) not working

### ISSUE THREAD

**Issue by jnachtigall** [poalrom/grunt-prettier#4]
This is not working (matches nothing):
```
{
    options: {
      singleQuote: true
    },
    files: {
      src: [
        '*.(js|json)',
        'tasks/**/*.(js|json)',
        'src/js/components/**/*.(js|json)'
      ]
    }
  }
```

according to the [glob documentation](https://github.com/isaacs/node-glob#glob-primer) this should be working (as far as I undertand it).

Changes to the following works:
```
{
    options: {
      singleQuote: true
    },
    files: {
      src: ['*.js', 'tasks/**/*.js', 'src/js/components/**/*.js']
    }
  }
```

Background is that next to using grunt, I also use `onchange` as described at https://prettier.io/docs/en/watching-files.html and there the above `globs` work perfectly and I do not seem to be able to reuse them in grunt-prettier. Here's my `package.json`:
```
  "scripts": {
    "startPrettierWatcher":
      "onchange \"*.(js|json)\" \"tasks/**/*.(js|json)\" \"src/components/**/*.(js|json)\" -- prettier --write {{changed}}",
  },
```

**Comment by jnachtigall** [comment]
Well, I think I got it wrong ;) 
```
'tasks/**/*.(js|json)',
```
should be (and then it works!):
```
'tasks/**/*{js,json}',
```

Sorry, for this noise and thanks for releasing 0.2 :)

**Comment by poalrom** [comment]
No problem =)
Thank you for using grunt-prettier
